
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserCreator, UserHeaderDisplay } from "taimidanseo/features/users/components/user-creator-component";
import { useUserStore } from "taimidanseo/features/users/user-store";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`  antialiased flex-1 flex flex-col  justify-start'
          
          `}
      >
        <header className="text-white w-full bg-green-400"><UserHeaderDisplay /></header>
        <UserCreator />
        {children}
      </body>
    </html>
  );
}
